DROP TABLE STUDENT CASCADE CONSTRAINTS;


CREATE TABLE STUDENT(
STUDENT_ID VARCHAR2(13),
STUDENT_NAME VARCHAR2 (30),
STUDENT_GENDER CHAR(1),
STUDENT_CREDITS NUMBER,
STUDERT_CGPA NUMBER,
STUDENT_DOB DATE,
STUDENT_PHONE CHAR(11)

);
SELECT * FROM STUDENT;

ALTER SESSION SET NLS_DATE_FORMAT = 'MM-DD-YYYY';

insert INTO STUDENT VALUES ('2022-1-60-001','ALICE','F',100,3.5,TO_DATE('04-03-2002','MM-DD-YYYY'),'01708922278');

insert INTO STUDENT VALUES ('2022-1-60-002','BOB','M',80,3.25,TO_DATE('12-21-2003','MM-DD-YYYY'),'01708926778');

insert INTO STUDENT VALUES ('2022-1-60-003','CAROL','F',35,3.9,TO_DATE('01-01-2004','MM-DD-YYYY'),'01704522278');

insert INTO STUDENT VALUES ('2022-1-60-004','DANNY','M',40,3.65,TO_DATE('10-30-2004','MM-DD-YYYY'),'01508956278');





-- born before 2004

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_DOB < TO_DATE('01-01-2004', 'MM-DD-YYYY');

--fELAME

SELECT STUDENT_NAME,STUDENT_GENDER
FROM STUDENT
WHERE STUDENT_GENDER='F';



--Select all student names

SELECT STUDENT_NAME 
FROM STUDENT;

--Select all male students

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_GENDER='M';

SELECT STUDENT_NAME AS MALE_STD
FROM STUDENT
WHERE STUDENT_GENDER='M';

SELECT STUDENT_NAME,STUDENT_GENDER
FROM STUDENT
WHERE STUDENT_GENDER='M';

--students who have more than 50 credits

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_CREDITS >50;


SELECT STUDENT_NAME,STUDENT_CREDITS
FROM STUDENT
WHERE STUDENT_CREDITS >50;


--students born after January 1, 2003.

SELECT STUDENT_NAME,STUDENT_DOB
FROM STUDENT
WHERE STUDENT_DOB > TO_DATE('01-01-2003','MM-DD-YYYY');


--born between January 1, 2003 and March 1, 2004

SELECT STUDENT_NAME,STUDENT_DOB
FROM STUDENT
WHERE student_dob BETWEEN TO_DATE('01-01-2003','MM-DD-YYYY')
AND TO_DATE('03-01-2004','MM-DD-YYYY');




--select students whose phone numbers start with '017'
SELECT STUDENT_NAME,STUDENT_PHONE
FROM STUDENT
WHERE STUDENT_PHONE LIKE '017%';

--END
SELECT STUDENT_NAME,STUDENT_PHONE
FROM STUDENT
WHERE STUDENT_PHONE LIKE '%778';


SELECT STUDENT_NAME,STUDENT_PHONE
FROM STUDENT
WHERE STUDENT_NAME LIKE '%B';


--START WITH A
SELECT STUDENT_NAME,STUDENT_iD
FROM STUDENT
WHERE STUDENT_NAME LIKE 'A%';

--END L
SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_NAME LIKE '%L';



--born in the year 2004

SELECT STUDENT_NAME,STUDENT_DOB
FROM STUDENT
WHERE EXTRACT(YEAR FROM STUDENT_DOB)=2004;


--COUNT

SELECT COUNT(*) AS TOTAL_STD
FROM STUDENT;



SELECT COUNT(*) AS TOTAL_STD03
FROM STUDENT
WHERE STUDENT_DOB > TO_DATE('01-01-2003','MM-DD-YYYY');

--Count how many male and female students are there

SELECT STUDENT_GENDER , COUNT(*) AS c
FROM STUDENT
GROUP BY STUDENT_GENDER ;



SELECT AVG(STUDERT_CGPA) AS AVGCG
FROM STUDENT;

SELECT STUDENT_GENDER, AVG(STUDERT_CGPA) AS AVGCG
FROM STUDENT
GROUP BY STUDENT_GENDER;

SELECT MAX(STUDERT_CGPA) AS MAXCG
FROM STUDENT;


SELECT STUDENT_NAME, STUDERT_CGPA
FROM STUDENT
WHERE STUDERT_CGPA = (SELECT MAX(STUDERT_CGPA) FROM STUDENT);


--name contains the letter ‘O’

SELECT STUDENT_NAME
FROM STUDENT
WHERE STUDENT_NAME LIKE '%O%';












