CREATE TABLE IF NOT EXISTS PRODUCTS(PRODUCT_ID INT , 
LOW_FATS enum('Y', 'N'),
RECYCLABLE enum('Y', 'N'))

Truncate TABLE PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE ) VALUES ('0','Y', 'N')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE ) VALUES ('1','Y', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE ) VALUES ('2','N', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE ) VALUES ('3','Y', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE ) VALUES ('4','N', 'N')
SELECT * FROM PRODUCTS;

select PRODUCT_ID
FROM PRODUCTS
WHERE LOW_FATS='Y' AND RECYCLABLE ='Y';