CREATE TABLE LIBRARY(
  LIBRARY_id VARCHAR2(10),
  NAME VARCHAR2(30),
  LOCATION VARCHAR(30),
  CAPACITY INT DEFAULT 500,
  CONSTRAINT LIB_ID_PK PRIMARY KEY(LIBRARY_id),
  CONSTRAINT CAP_CHK CHECK(CAPACITY>0)


);


CREATE TABLE BOOK(
 book_id VARCHAR2(10),
  title VARCHAR2(30) NOT NULL,
  LIB_id  VARCHAR(10),
  COPIES INT DEFAULT 1,
  PRIMARY KEY ( book_id),
  CONSTRAINT LIB_ID_FK FOREIGN KEY( LIB_id )
  REFERENCES LIBRARY ( LIBRARY_id ),
  CHECK (COPIES>=1)


);
--drop table cascade constraints

INSERT INTO LIBRARY VALUES ('L01','DR.S.R. LASKAR' ,'EWU',2000);
INSERT INTO LIBRARY(LIBRARY_id,NAME) VALUES('L02', 'XYZ');

SELECT *FROM  LIBRARY;


INSERT iNTO BOOK VALUES('BOK-1','HIMU','L01',1);
INSERT iNTO BOOK VALUES('BOOK-1','OPEKKHA','L02',1);
SELECT *FROM  BOOK;
SELECT * FROM user_cons_columns WHERE TABLE_NAME = 'BOOK';

SELECT SYSTIMESTAMP FROM DUAL;
ALTER TABLE BOOK ADD PUBLISHING_DATE DATE;
ALTER TABLE BOOK MODIFY PUBLISHING_DATE DATE;
ALTER TABLE BOOK DROP COLUMN PUBLISHING_DATE ;


--CROSS JOIN

SELECT *FROM LIBRARY,BOOK;

SELECT *FROM LIBRARY L,BOOK B
WHERE L.LIBRARY_id=B.LIB_iD   
;

--NATUAL JOIN

SELECT *FROM LIBRARY NATURAL JOIN BOOK;
